#!/usr/bin/env python3
"""
ollama-meta-qa.py — read-only QA of every public page's <title> and meta
description. Deterministic checks (length, duplicates, forbidden claims) always
run; a LOCAL Ollama model adds a short second opinion per page when reachable.
Never calls cloud models and never edits HTML.

Usage (repo root):
  python3 scripts/ollama-meta-qa.py [--model qwen2.5:1.5b] [--no-llm]
Writes docs/meta-qa-report.md. Exit 1 if any deterministic check fails.
"""
import argparse, glob, html, json, re, sys, urllib.request

OLLAMA = 'http://localhost:11434/api/chat'
REPORT = 'docs/meta-qa-report.md'
SKIP = re.compile(r'(^|/)(preview|products-section|404)\.html$|^(admin|tina|tests|node_modules)/')
CLAIMS = [
    ('price', re.compile(r'\$\s?\d', re.I)),
    ('rating', re.compile(r'\b\d(?:\.\d)?\s*(?:stars?|/\s*5)\b|\b\d+\+?\s*reviews?\b', re.I)),
    ('lifetime', re.compile(r'\blifetime\b', re.I)),
]
PROMPT = """You review SEO copy for a vehicle upfitting shop in Rockville, MD.
Reply with ONE short line: "OK" if the title and description are clear and
specific to the page, otherwise "FIX: <reason in under 15 words>".

Page: {page}
Title: {title}
Description: {desc}"""


def extract(path):
    s = open(path, encoding='utf-8').read()
    t = re.search(r'<title>(.*?)</title>', s, re.S)
    d = re.search(r'<meta name="description" content="([^"]*)"', s)
    return (html.unescape(t.group(1).strip()) if t else '',
            html.unescape(d.group(1).strip()) if d else '')


def ask(model, page, title, desc):
    body = json.dumps({'model': model, 'stream': False, 'options': {'temperature': 0},
                       'messages': [{'role': 'user', 'content': PROMPT.format(page=page, title=title, desc=desc)}]}).encode()
    req = urllib.request.Request(OLLAMA, body, {'Content-Type': 'application/json'})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.load(r)['message']['content'].strip().splitlines()[0][:160]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--model', default='qwen2.5:1.5b')
    ap.add_argument('--no-llm', action='store_true')
    a = ap.parse_args()

    pages = sorted(p for p in glob.glob('*.html') + glob.glob('*/*.html') if not SKIP.search(p))
    rows, fails, seen_t, seen_d = [], 0, {}, {}
    for p in pages:
        title, desc = extract(p)
        issues = []
        if not 30 <= len(title) <= 65: issues.append(f'title {len(title)} chars')
        if not 70 <= len(desc) <= 160: issues.append(f'description {len(desc)} chars')
        if title in seen_t: issues.append(f'duplicate title of {seen_t[title]}')
        if desc in seen_d: issues.append(f'duplicate description of {seen_d[desc]}')
        seen_t.setdefault(title, p); seen_d.setdefault(desc, p)
        for name, rx in CLAIMS:
            if rx.search(title + ' ' + desc): issues.append(f'claim:{name} (owner-approved?)')
        hard = [i for i in issues if not i.startswith('claim:')]
        fails += bool(hard)
        llm = '-'
        if not a.no_llm:
            try: llm = ask(a.model, p, title, desc)
            except Exception as e: llm = f'(ollama unavailable: {type(e).__name__})'
        rows.append((p, len(title), len(desc), '; '.join(issues) or 'ok', llm))
        print(f'{p}: {rows[-1][3]} | {llm}', flush=True)

    with open(REPORT, 'w', encoding='utf-8') as fh:
        fh.write('# Title / meta description QA\n\n')
        fh.write(f'Generated by `scripts/ollama-meta-qa.py` (local model: `{"none" if a.no_llm else a.model}`). '
                 'Deterministic checks gate; the model column is advisory only.\n\n')
        fh.write('| Page | Title len | Desc len | Checks | Local model note |\n|---|---|---|---|---|\n')
        for r in rows:
            fh.write('| %s | %d | %d | %s | %s |\n' % (r[0], r[1], r[2], r[3], r[4].replace('|', '/')))
    print(f'\n{len(pages)} pages, {fails} with failing checks -> {REPORT}')
    sys.exit(1 if fails else 0)


if __name__ == '__main__':
    main()
